image: node:18

stages:
  - build
  - sonar
  - deploy
  - release

include:
  - project: "plattform/brm/gitlab-pipelines"
    ref: main
    file: "snippets/general/workflow.gitlab-ci.yml"
  - project: "plattform/brm/gitlab-pipelines"
    ref: main
    file: "snippets/general/release.gitlab-ci.yml"
  - project: "plattform/brm/gitlab-pipelines"
    ref: main
    file: "snippets/typescript/deploy.gitlab-ci.yml"

# run a npm install to check if every dependency works
build:
  stage: build
  image: node:18
  script:
    - node -v
    - npm -v
    - npm install
  interruptible: true
  artifacts:
    when: always
    paths:
      - index.mjs
      - README.md
      - package.json
      - package-lock.json
    expire_in: 5 days

publish_on_nexus:
  needs:
    - build
  dependencies:
    - build

deploy_on_gitlab_project:
  needs:
    - build
  dependencies:
    - build

deploy_on_gitlab_general:
  needs:
    - build
  dependencies:
    - build
